
services:
  php-apache:
    container_name: php-apache
    restart: unless-stopped
    build:
      context: .              
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./Tasks:/var/www/html/     
    ports:
      - 8001:80                  

  db:
    container_name: db
    image: mysql                  
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Heslo11
    ports:
      - 9906:3306                

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    ports:
      - 8080:80                   
    restart: unless-stopped
    environment:
      PMA_HOST: db
    depends_on:
      - db
